import { prefixary } from "../utils";

export default prefixary({
    "accessor-pairs": "warn",
    "array-callback-return": "warn",
    "arrow-body-style": "off",
    "block-scoped-var": "warn",
    "camelcase": "off",
    "capitalized-comments": "off",
    "class-methods-use-this": "off",
    "complexity": "off",
    "consistent-return": "off",
    "curly": ["warn", "multi-line"],
    "default-case": "off",
    "default-case-last": "warn",
    "default-param-last": "warn",
    "dot-notation": ["warn", {
        allowPattern: "^[a-z]+(_[a-z]+)+$"
    }],
    "eqeqeq": ["warn", "smart"],
    "func-name-matching": "off",
    "func-names": "off",
    "func-style": ["warn", "declaration", {
        allowArrowFunctions: true
    }],
    "grouped-accessor-pairs": "off",
    "guard-for-in": "off",
    "id-denylist": "off",
    "id-length": "off",
    "id-match": "off",
    "init-declarations": "off",
    "logical-assignment-operators": "warn",
    "max-classes-per-file": "off",
    "max-depth": "off",
    "max-lines": "off",
    "max-lines-per-function": "off",
    "max-nested-callbacks": "off",
    "max-params": "off",
    "max-statements": "off",
    "multiline-comment-style": "warn",
    "new-cap": "warn",
    "no-alert": "warn",
    "no-array-constructor": "warn",
    "no-await-in-loop": "off",
    "no-bitwise": "off",
    "no-caller": "off",
    "no-console": "off",
    "no-constructor-return": "warn",
    "no-continue": "off",
    "no-div-regex": "off",
    "no-duplicate-imports": "warn",
    "no-else-return": "off",
    "no-empty-function": "off",
    "no-eq-null": "off",
    "no-eval": "warn",
    "no-extend-native": "warn",
    "no-extra-bind": "warn",
    "no-extra-label": "off",
    "no-implicit-coercion": "off",
    "no-implicit-globals": "off",
    "no-implied-eval": "warn",
    "no-inline-comments": "off",
    "no-inner-declarations": "off",
    "no-invalid-this": "off",
    "no-iterator": "warn",
    "no-label-var": "off",
    "no-labels": "off",
    "no-lone-blocks": "warn",
    "no-lonely-if": "warn",
    "no-loop-func": "warn",
    "no-magic-numbers": "off",
    "no-multi-assign": ["warn", {
        ignoreNonDeclaration: true
    }],
    "no-multi-str": "warn",
    "no-negated-condition": "off",
    "no-nested-ternary": "off",
    "no-new": "warn",
    "no-new-func": "warn",
    "no-new-wrappers": "warn",
    "no-object-constructor": "warn",
    "no-octal-escape": "warn",
    "no-param-reassign": "off",
    "no-plusplus": "off",
    "no-promise-executor-return": "warn",
    "no-proto": "warn",
    "no-restricted-exports": "off",
    "no-restricted-globals": "off",
    "no-restricted-imports": "off",
    "no-restricted-properties": "off",
    "no-restricted-syntax": "off",
    "no-return-assign": "warn",
    "no-script-url": "off",
    "no-self-compare": "warn",
    "no-sequences": "off",
    "no-shadow": "off",
    "no-template-curly-in-string": "off",
    "no-ternary": "off",
    "no-throw-literal": "off",
    "no-undef-init": "warn",
    "no-undefined": "warn",
    "no-underscore-dangle": "off",
    "no-unmodified-loop-condition": "warn",
    "no-unneeded-ternary": ["warn", {
        defaultAssignment: false
    }],
    "no-unreachable-loop": "warn",
    "no-unused-expressions": "off",
    "no-unused-private-class-members": "warn",
    "no-use-before-define": "off",
    "no-useless-assignment": "off",
    "no-useless-call": "warn",
    "no-useless-computed-key": "warn",
    "no-useless-concat": "warn",
    "no-useless-constructor": "warn",
    "no-useless-rename": "warn",
    "no-useless-return": "warn",
    "no-var": "warn",
    "no-void": "off",
    "no-warning-comments": "off",
    "object-shorthand": ["warn", "methods"],
    "one-var": ["warn", {
        initialized: "never"
    }],
    "operator-assignment": ["warn", "always"],
    "prefer-arrow-callback": ["warn", {
        allowNamedFunctions: false,
        allowUnboundThis: true
    }],
    "prefer-const": ["warn", {
        destructuring: "all",
        ignoreReadBeforeAssign: false
    }],
    "prefer-destructuring": "off",
    "prefer-exponentiation-operator": "warn",
    "prefer-named-capture-group": "off",
    "prefer-numeric-literals": "warn",
    "prefer-object-has-own": "warn",
    "prefer-object-spread": "warn",
    "prefer-promise-reject-errors": "warn",
    "prefer-regex-literals": ["warn", {
        disallowRedundantWrapping: true
    }],
    "prefer-rest-params": "warn",
    "prefer-spread": "warn",
    "prefer-template": "off",
    "radix": "off",
    "require-atomic-updates": "off",
    "require-await": "off",
    "require-unicode-regexp": "off",
    "sort-imports": "warn",
    "sort-keys": "off",
    "sort-vars": "off",
    "strict": "off",
    "symbol-description": "off",
    "vars-on-top": "warn",
    "yoda": ["warn", "never", {
        exceptRange: true
    }]
});