import type { Rules } from "@antfu/eslint-config";
import javascript from "../configs/javascript";
import stylistic from "../configs/stylistic";

export default <Rules> {
    // Priority A
    "vue/no-arrow-functions-in-watch": "warn",
    "vue/no-async-in-computed-properties": "warn",
    "vue/no-child-content": "warn",
    "vue/no-computed-properties-in-data": "warn",
    "vue/no-deprecated-data-object-declaration": "warn",
    "vue/no-deprecated-delete-set": "warn",
    "vue/no-deprecated-destroyed-lifecycle": "warn",
    "vue/no-deprecated-dollar-listeners-api": "warn",
    "vue/no-deprecated-dollar-scopedslots-api": "warn",
    "vue/no-deprecated-events-api": "warn",
    "vue/no-deprecated-filter": "warn",
    "vue/no-deprecated-functional-template": "warn",
    "vue/no-deprecated-html-element-is": "warn",
    "vue/no-deprecated-inline-template": "warn",
    "vue/no-deprecated-props-default-this": "warn",
    "vue/no-deprecated-router-link-tag-prop": "warn",
    "vue/no-deprecated-scope-attribute": "warn",
    "vue/no-deprecated-slot-attribute": "warn",
    "vue/no-deprecated-slot-scope-attribute": "warn",
    "vue/no-deprecated-v-bind-sync": "warn",
    "vue/no-deprecated-v-is": "warn",
    "vue/no-deprecated-v-on-native-modifier": "warn",
    "vue/no-deprecated-v-on-number-modifiers": "warn",
    "vue/no-deprecated-vue-config-keycodes": "warn",
    "vue/no-dupe-keys": "warn",
    "vue/no-dupe-v-else-if": "warn",
    "vue/no-duplicate-attributes": "warn",
    "vue/no-export-in-script-setup": "warn",
    "vue/no-expose-after-await": "warn",
    "vue/no-lifecycle-after-await": "warn",
    "vue/no-mutating-props": "warn",
    "vue/no-parsing-error": "warn",
    "vue/no-ref-as-operand": "warn",
    "vue/no-reserved-component-names": "warn",
    "vue/no-reserved-keys": "warn",
    "vue/no-reserved-props": "warn",
    "vue/no-shared-component-data": "warn",
    "vue/no-side-effects-in-computed-properties": "warn",
    "vue/no-template-key": "warn",
    "vue/no-textarea-mustache": "warn",
    "vue/no-unused-components": "warn",
    "vue/no-unused-vars": "warn",
    "vue/no-use-computed-property-like-method": "warn",
    "vue/no-use-v-if-with-v-for": "warn",
    "vue/no-useless-template-attributes": "warn",
    "vue/no-v-for-template-key-on-child": "warn",
    "vue/no-v-text-v-html-on-component": "warn",
    "vue/no-watch-after-await": "warn",
    "vue/prefer-import-from-vue": "warn",
    "vue/require-component-is": "warn",
    "vue/require-prop-type-constructor": "warn",
    "vue/require-render-return": "warn",
    "vue/require-slots-as-functions": "warn",
    "vue/require-toggle-inside-transition": "warn",
    "vue/require-valid-default-prop": "warn",
    "vue/return-in-emits-validator": "warn",
    "vue/use-v-on-exact": "warn",
    "vue/valid-attribute-name": "warn",
    "vue/valid-define-emits": "warn",
    "vue/valid-define-props": "warn",
    "vue/valid-next-tick": "warn",
    "vue/valid-template-root": "warn",
    "vue/valid-v-bind": "warn",
    "vue/valid-v-cloak": "warn",
    "vue/valid-v-else-if": "warn",
    "vue/valid-v-else": "warn",
    "vue/valid-v-html": "warn",
    "vue/valid-v-if": "warn",
    "vue/valid-v-memo": "warn",
    "vue/valid-v-model": "warn",
    "vue/valid-v-on": "warn",
    "vue/valid-v-once": "warn",
    "vue/valid-v-pre": "warn",
    "vue/valid-v-show": "warn",
    "vue/valid-v-slot": "warn",
    "vue/valid-v-text": "warn",

    // Priority B
    "vue/attribute-hyphenation": "warn",
    "vue/component-definition-name-casing": ["warn", "kebab-case"],
    "vue/first-attribute-linebreak": ["warn", {
        singleline: "beside",
        multiline: "below",
    }],
    "vue/html-closing-bracket-newline": ["warn", {
        singleline: "never",
        multiline: "always",
    }],
    "vue/html-end-tags": "warn",
    "vue/html-indent": ["warn", 4],
    "vue/html-quotes": ["warn", "double"],
    "vue/html-self-closing": ["warn", {
        html: {
            void: "always",
            normal: "never",
            component: "always",
        },
        svg: "always",
        math: "always",
    }],
    "vue/mustache-interpolation-spacing": ["warn", "always"],
    "vue/no-multi-spaces": "warn",
    "vue/no-spaces-around-equal-signs-in-attribute": "warn",
    "vue/no-template-shadow": "warn",
    "vue/one-component-per-file": "warn",
    "vue/prop-name-casing": ["warn", "camelCase"],
    "vue/require-prop-types": "warn",
    "vue/v-bind-style": ["warn", "shorthand", {
        sameNameShorthand: "always",
    }],
    "vue/v-on-event-hyphenation": ["warn", "always"],
    "vue/v-on-style": ["warn", "shorthand"],
    "vue/v-slot-style": ["warn", {
        atComponent: "v-slot",
        default: "shorthand",
        named: "shorthand",
    }],

    // Priority C
    "vue/attributes-order": ["warn", {
        order: [
            "LIST_RENDERING",
            "CONDITIONALS",
            "RENDER_MODIFIERS",
            "OTHER_DIRECTIVES",
            "SLOT",
            "DEFINITION",
            "UNIQUE",
            "GLOBAL",
            ["ATTR_DYNAMIC", "ATTR_STATIC", "ATTR_SHORTHAND_BOOL"],
            "TWO_WAY_BINDING",
            "EVENTS",
            "CONTENT",
        ],
    }],
    "vue/no-lone-template": "warn",
    "vue/no-multiple-slot-args": "warn",
    "vue/order-in-components": "warn",
    "vue/this-in-template": ["warn", "never"],

    // Uncategorized
    "vue/block-order": ["warn", {
        order: [
            "script",
            "template",
            "style",
        ],
    }],
    "vue/block-tag-newline": ["warn", {
        singleline: "always",
        multiline: "always",
    }],
    "vue/comma-dangle": ["warn", "never"],
    "vue/component-api-style": ["warn", [
        "script-setup",
        "composition",
    ]],
    "vue/component-name-in-template-casing": ["warn", "kebab-case", {
        registeredComponentsOnly: false,
    }],
    "vue/component-options-name-casing": ["warn", "PascalCase"],
    "vue/custom-event-name-casing": ["warn", "camelCase"],
    "vue/define-emits-declaration": ["warn", "type-literal"],
    "vue/define-macros-order": ["warn", {
        order: [
            "defineOptions",
            "defineProps",
            "defineModel",
            "defineEmits",
            "defineSlots",
        ],
        defineExposeLast: true,
    }],
    "vue/define-props-declaration": ["warn", "type-based"],
    "vue/html-comment-content-newline": ["warn", {
        singleline: "never",
        multiline: "always",
    }],
    "vue/html-comment-content-spacing": ["warn", "always"],
    "vue/html-comment-indent": ["warn", 4],
    "vue/no-deprecated-model-definition": "warn",
    "vue/no-duplicate-attr-inheritance": "warn",
    "vue/no-empty-component-block": "warn",
    "vue/no-import-compiler-macros": "warn",
    "vue/no-multiple-objects-in-class": "warn",
    "vue/no-potential-component-option-typo": ["warn", {
        presets: ["all"],
    }],
    "vue/no-required-prop-with-default": ["warn", {
        autofix: true,
    }],
    "vue/no-static-inline-styles": "warn",
    "vue/no-this-in-before-route-enter": "warn",
    "vue/no-unused-refs": "warn",
    "vue/no-unused-emit-declarations": "warn",
    "vue/no-use-v-else-with-v-for": "warn",
    "vue/no-useless-mustaches": ["warn", {
        ignoreIncludesComment: true,
        ignoreStringEscape: true,
    }],
    "vue/no-useless-v-bind": ["warn", {
        ignoreIncludesComment: true,
        ignoreStringEscape: true,
    }],
    "vue/padding-line-between-blocks": ["warn", "always"],
    "vue/prefer-define-options": "warn",
    "vue/prefer-prop-type-boolean-first": "warn",
    "vue/prefer-separate-static-class": "warn",
    "vue/prefer-use-template-ref": "warn",
    "vue/prefer-true-attribute-shorthand": ["warn", "always"],
    "vue/require-default-export": "warn",
    "vue/require-direct-export": "warn",
    "vue/require-emit-validator": "warn",
    "vue/require-explicit-emits": "warn",
    "vue/require-macro-variable-name": "warn",
    "vue/require-typed-object-prop": "warn",
    "vue/require-typed-ref": "warn",
    "vue/valid-define-options": "warn",
    "vue/v-for-delimiter-style": ["warn", "in"],

    // Extension
    ...Object.fromEntries(([
        "camelcase",
        "dot-notation",
        "eqeqeq",
        "no-console",
        "no-constant-condition",
        "no-empty-pattern",
        "no-implicit-coercion",
        "no-irregular-whitespace",
        "no-loss-of-precision",
        "no-restricted-syntax",
        "no-sparse-arrays",
        "no-useless-concat",
        "object-shorthand",
        "prefer-template",
    ] as const).map((rule) => [`vue/${rule}`, javascript.rules![rule]])),

    ...Object.fromEntries(([
        "array-bracket-newline",
        "array-bracket-spacing",
        "array-element-newline",
        "arrow-spacing",
        "block-spacing",
        "brace-style",
        "comma-dangle",
        "comma-spacing",
        "comma-style",
        "dot-location",
        "key-spacing",
        "keyword-spacing",
        "max-len",
        "multiline-ternary",
        "no-extra-parens",
        "object-curly-newline",
        "object-curly-spacing",
        "object-property-newline",
        "operator-linebreak",
        "quote-props",
        "space-in-parens",
        "space-infix-ops",
        "space-unary-ops",
        "template-curly-spacing",
    ] as const).map((rule) => [`vue/${rule}`, stylistic.rules![`style/${rule}`]])),

    // Conflict with Nuxt
    "vue/no-undef-components": "off",
    "vue/require-name-property": "off",

    // Have spacial cases
    "vue/no-ref-object-reactivity-loss": "off",
    "vue/no-root-v-if": "off",
    "vue/no-setup-props-reactivity-loss": "off",
    "vue/no-unused-properties": "off",

    // Lack of personalization
    "vue/html-closing-bracket-spacing": "off",
    "vue/script-indent": "off",

    // Should be delegated
    "vue/no-restricted-block": "off",
    "vue/no-restricted-call-after-await": "off",
    "vue/no-restricted-class": "off",
    "vue/no-restricted-component-names": "off",
    "vue/no-restricted-component-options": "off",
    "vue/no-restricted-custom-event": "off",
    "vue/no-restricted-html-elements": "off",
    "vue/no-restricted-props": "off",
    "vue/no-restricted-static-attribute": "off",
    "vue/no-restricted-v-bind": "off",
    "vue/no-restricted-v-on": "off",

    // Should loose
    "vue/block-lang": "off",
    "vue/enforce-style-attribute": "off",
    "vue/max-attributes-per-line": "off",
    "vue/max-lines-per-block": "off",
    "vue/max-props": "off",
    "vue/max-template-depth": "off",
    "vue/multi-word-component-names": "off",
    "vue/multiline-html-element-content-newline": "off",
    "vue/next-tick-style": "off",
    "vue/new-line-between-multi-line-property": "off",
    "vue/no-multiple-template-root": "off",
    "vue/no-v-html": "off",
    "vue/no-v-text": "off",
    "vue/padding-line-between-tags": "off",
    "vue/padding-lines-in-component-definition": "off",
    "vue/require-default-prop": "off",
    "vue/require-explicit-slots": "off",
    "vue/require-expose": "off",
    "vue/require-prop-comment": "off",
    "vue/require-v-for-key": "off",
    "vue/return-in-computed-property": "off",
    "vue/singleline-html-element-content-newline": "off",
    "vue/slot-name-casing": "off",
    "vue/sort-keys": "off",
    "vue/static-class-names-order": "off",
    "vue/v-on-handler-style": "off",
    "vue/valid-v-for": "off",

    // Too narrow
    "vue/html-button-has-type": "off",
    "vue/match-component-file-name": "off",
    "vue/match-component-import-name": "off",
    "vue/no-bare-strings-in-template": "off",
    "vue/no-boolean-default": "off",
    "vue/no-template-target-blank": "off",

    // TS instead of
    "vue/no-undef-properties": "off",
    "vue/no-unsupported-features": "off",

    // Useless in Vue 3
    "vue/v-if-else-key": "off",
    "vue/valid-v-is": "off",
};
