import type { TypedFlatConfigItem } from "@antfu/eslint-config";

export default <TypedFlatConfigItem> {
    name: "zin/stylistic/rules",
    rules: {
        "style/array-bracket-newline": ["warn", "consistent"],
        "style/array-bracket-spacing": "warn",
        "style/array-element-newline": ["warn", "consistent"],
        "style/arrow-parens": ["warn", "always"],
        "style/arrow-spacing": "warn",
        "style/block-spacing": "warn",
        "style/brace-style": ["warn", "stroustrup"],
        "style/comma-dangle": ["warn", "always-multiline"],
        "style/comma-spacing": "warn",
        "style/comma-style": "warn",
        "style/computed-property-spacing": "warn",
        "style/curly-newline": "off",
        "style/dot-location": ["warn", "property"],
        "style/eol-last": "warn",
        "style/function-call-argument-newline": ["warn", "consistent"],
        "style/function-call-spacing": "warn",
        "style/function-paren-newline": ["warn", "consistent"],
        "style/generator-star-spacing": ["warn", {
            named: "after",
            anonymous: "before",
            method: "both",
        }],
        "style/implicit-arrow-linebreak": "warn",
        "style/indent-binary-ops": "off",
        "style/indent": "off",
        "style/key-spacing": "warn",
        "style/keyword-spacing": "warn",
        "style/line-comment-position": "off",
        "style/linebreak-style": "warn",
        "style/lines-around-comment": "off",
        "style/lines-between-class-members": ["warn", "always", {
            exceptAfterSingleLine: true,
        }],
        "style/max-len": "off",
        "style/max-statements-per-line": "off",
        "style/member-delimiter-style": ["warn", {
            multiline: {
                delimiter: "semi",
                requireLast: true,
            },
        }],
        "style/multiline-comment-style": "off",
        "style/multiline-ternary": "off",
        "style/new-parens": "warn",
        "style/newline-per-chained-call": "off",
        "style/no-confusing-arrow": "warn",
        "style/no-extra-parens": ["warn", "functions"],
        "style/no-extra-semi": "warn",
        "style/no-floating-decimal": "warn",
        "style/no-mixed-operators": "off",
        "style/no-mixed-spaces-and-tabs": "warn",
        "style/no-multi-spaces": ["warn", {
            ignoreEOLComments: true,
        }],
        "style/no-multiple-empty-lines": ["warn", {
            max: 1,
        }],
        "style/no-tabs": "warn",
        "style/no-trailing-spaces": "warn",
        "style/no-whitespace-before-property": "warn",
        "style/nonblock-statement-body-position": "warn",
        "style/object-curly-newline": "warn",
        "style/object-curly-spacing": ["warn", "always"],
        "style/object-property-newline": ["warn", {
            allowAllPropertiesOnSameLine: true,
        }],
        "style/one-var-declaration-per-line": "off",
        "style/operator-linebreak": "off",
        "style/padded-blocks": ["warn", "never"],
        "style/padding-line-between-statements": "off",
        "style/quote-props": ["warn", "as-needed"],
        "style/quotes": ["warn", "double", {
            allowTemplateLiterals: "always",
        }],
        "style/rest-spread-spacing": "warn",
        "style/semi-spacing": "warn",
        "style/semi-style": "warn",
        "style/semi": ["warn", "always"],
        "style/space-before-blocks": "warn",
        "style/space-before-function-paren": ["warn", {
            named: "never",
            anonymous: "never",
        }],
        "style/space-in-parens": "warn",
        "style/space-infix-ops": "warn",
        "style/space-unary-ops": "warn",
        "style/spaced-comment": "off",
        "style/switch-colon-spacing": "warn",
        "style/template-curly-spacing": "warn",
        "style/template-tag-spacing": "warn",
        "style/type-annotation-spacing": "warn",
        "style/type-generic-spacing": "warn",
        "style/type-named-tuple-spacing": "warn",
        "style/wrap-iife": ["warn", "inside", {
            functionPrototypeMethods: true,
        }],
        "style/wrap-regex": "off",
        "style/yield-star-spacing": "warn",
    },
};
