import { withPrefix } from "../utils/index.js";

export default withPrefix("vue", {
    "attribute-hyphenation": "warn",
    "attributes-order": ["warn", {
        order: [
            "LIST_RENDERING",
            "CONDITIONALS",
            "RENDER_MODIFIERS",
            "OTHER_DIRECTIVES",
            "SLOT",
            "DEFINITION",
            "UNIQUE",
            "GLOBAL",
            ["ATTR_DYNAMIC", "ATTR_STATIC", "ATTR_SHORTHAND_BOOL"],
            "TWO_WAY_BINDING",
            "EVENTS",
            "CONTENT"
        ]
    }],
    "component-definition-name-casing": ["warn", "kebab-case"],
    "first-attribute-linebreak": ["warn", {
        singleline: "beside",
        multiline: "below"
    }],
    "html-closing-bracket-newline": ["warn", {
        singleline: "never",
        multiline: "always"
    }],
    "html-quotes": ["warn", "double"],
    "html-self-closing": ["warn", {
        html: {
            void: "always",
            normal: "never",
            component: "always"
        },
        svg: "always",
        math: "always"
    }],
    "mustache-interpolation-spacing": ["warn", "always"],
    "no-dupe-keys": "warn",
    "no-dupe-v-else-if": "warn",
    "no-duplicate-attributes": "warn",
    "no-export-in-script-setup": "warn",
    "no-expose-after-await": "warn",
    "no-lifecycle-after-await": "warn",
    "no-lone-template": "warn",
    "no-mutating-props": "warn",
    "no-multiple-slot-args": "warn",
    "no-multi-spaces": "warn",
    "no-ref-as-operand": "warn",
    "no-reserved-component-names": "warn",
    "no-reserved-keys": "warn",
    "no-reserved-props": "warn",
    "no-side-effects-in-computed-properties": "warn",
    "no-spaces-around-equal-signs-in-attribute": "warn",
    "no-template-key": "warn",
    "no-template-shadow": "warn",
    "no-textarea-mustache": "warn",
    "no-unused-vars": "warn",
    "no-use-computed-property-like-method": "warn",
    "no-use-v-if-with-v-for": "warn",
    "no-useless-template-attributes": "warn",
    "no-v-for-template-key-on-child": "warn",
    "no-v-text-v-html-on-component": "warn",
    "no-watch-after-await": "warn",
    "one-component-per-file": "warn",
    "prefer-import-from-vue": "warn",
    "prop-name-casing": ["warn", "camelCase"],
    "require-component-is": "warn",
    "require-explicit-emits": "warn",
    "require-prop-type-constructor": "warn",
    "require-render-return": "warn",
    "require-slots-as-functions": "warn",
    "require-toggle-inside-transition": "warn",
    "require-valid-default-prop": "warn",
    "return-in-computed-property": "warn",
    "return-in-emits-validator": "warn",
    "this-in-template": ["warn", "never"],
    "use-v-on-exact": "warn",
    "valid-attribute-name": "warn",
    "valid-define-emits": "warn",
    "valid-define-props": "warn",
    "valid-next-tick": "warn",
    "valid-v-bind": "warn",
    "valid-v-cloak": "warn",
    "valid-v-else-if": "warn",
    "valid-v-else": "warn",
    "valid-v-html": "warn",
    "valid-v-if": "warn",
    "valid-v-memo": "warn",
    "valid-v-model": "warn",
    "valid-v-on": "warn",
    "valid-v-once": "warn",
    "valid-v-pre": "warn",
    "valid-v-show": "warn",
    "valid-v-slot": "warn",
    "valid-v-text": "warn",
    "v-bind-style": ["warn", "shorthand"],
    "v-on-style": ["warn", "shorthand"]
});