import stylistic from "eslint-plugin-css-stylistic";
import type { ConfigObject } from "@eslint/config-helpers";

export default <ConfigObject> {
  name: "zin/css/stylistic",
  files: [
    "**/*.css",
  ],
  plugins: {
    "css-stylistic": stylistic,
  },
  rules: {
    "css-stylistic/at-rule-name-case": ["warn", "lower"],
    "css-stylistic/at-rule-name-newline-after": ["warn", "always-multi-line"],
    "css-stylistic/at-rule-name-space-after": ["warn", "always"],
    "css-stylistic/at-rule-semicolon-newline-after": ["warn", "always"],
    "css-stylistic/at-rule-semicolon-space-before": ["warn", "never"],
    "css-stylistic/block-closing-brace-empty-line-before": ["warn", "never"],
    "css-stylistic/block-closing-brace-newline-after": ["warn", "always"],
    "css-stylistic/block-closing-brace-newline-before": ["warn", "always-multi-line"],
    "css-stylistic/block-closing-brace-space-before": ["warn", "always-single-line"],
    "css-stylistic/block-opening-brace-newline-after": ["warn", "always-multi-line"],
    "css-stylistic/block-opening-brace-space-after": ["warn", "always-single-line"],
    "css-stylistic/block-opening-brace-space-before": ["warn", "always"],
    "css-stylistic/color-hex-case": ["warn", "upper"],
    "css-stylistic/declaration-bang-space-after": ["warn", "never"],
    "css-stylistic/declaration-bang-space-before": ["warn", "always"],
    "css-stylistic/declaration-block-semicolon-newline-after": ["warn", "always"],
    "css-stylistic/declaration-block-semicolon-newline-before": ["warn", "never-multi-line"],
    "css-stylistic/declaration-block-semicolon-space-after": ["warn", "always-single-line"],
    "css-stylistic/declaration-block-semicolon-space-before": ["warn", "never"],
    "css-stylistic/declaration-block-trailing-semicolon": ["warn", "always"],
    "css-stylistic/declaration-colon-newline-after": ["warn", "always-multi-line"],
    "css-stylistic/declaration-colon-space-after": ["warn", "always-single-line"],
    "css-stylistic/function-comma-space-after": ["warn", "always-single-line"],
    "css-stylistic/function-comma-space-before": ["warn", "never"],
    "css-stylistic/function-parentheses-newline-inside": ["warn", "always-multi-line"],
    "css-stylistic/function-parentheses-space-inside": ["warn", "never-single-line"],
    "css-stylistic/function-whitespace-after": ["warn", "always"],
    "css-stylistic/indentation": ["warn", 2, {
      baseIndentLevel: "auto",
    }],
    "css-stylistic/linebreaks": ["warn", "unix"],
    "css-stylistic/media-feature-colon-space-after": ["warn", "always"],
    "css-stylistic/media-feature-colon-space-before": ["warn", "never"],
    "css-stylistic/media-feature-name-case": ["warn", "lower"],
    "css-stylistic/media-feature-parentheses-space-inside": ["warn", "never"],
    "css-stylistic/media-feature-range-operator-space-after": ["warn", "always"],
    "css-stylistic/media-feature-range-operator-space-before": ["warn", "always"],
    "css-stylistic/media-query-list-comma-newline-after": ["warn", "always-multi-line"],
    "css-stylistic/media-query-list-comma-space-after": ["warn", "always-single-line"],
    "css-stylistic/media-query-list-comma-space-before": ["warn", "never"],
    "css-stylistic/named-grid-areas-alignment": ["warn", true],
    "css-stylistic/no-empty-first-line": ["warn", true],
    "css-stylistic/no-eol-whitespace": ["warn", true],
    "css-stylistic/no-extra-semicolons": ["warn", true],
    "css-stylistic/no-missing-end-of-source-newline": ["warn", true],
    "css-stylistic/number-leading-zero": ["warn", "always"],
    "css-stylistic/number-no-trailing-zeros": ["warn", true],
    "css-stylistic/property-case": ["warn", "lower"],
    "css-stylistic/selector-attribute-brackets-space-inside": ["warn", "never"],
    "css-stylistic/selector-attribute-operator-space-after": ["warn", "never"],
    "css-stylistic/selector-attribute-operator-space-before": ["warn", "never"],
    "css-stylistic/selector-combinator-space-after": ["warn", "always"],
    "css-stylistic/selector-combinator-space-before": ["warn", "always"],
    "css-stylistic/selector-descendant-combinator-no-non-space": ["warn", true],
    "css-stylistic/selector-list-comma-newline-after": ["warn", "always-multi-line"],
    "css-stylistic/selector-list-comma-space-after": ["warn", "always-single-line"],
    "css-stylistic/selector-list-comma-space-before": ["warn", "never"],
    "css-stylistic/selector-pseudo-class-case": ["warn", "lower"],
    "css-stylistic/selector-pseudo-class-parentheses-space-inside": ["warn", "never"],
    "css-stylistic/selector-pseudo-element-case": ["warn", "lower"],
    "css-stylistic/string-quotes": ["warn", "double"],
    "css-stylistic/unit-case": ["warn", "lower"],
    "css-stylistic/value-list-comma-space-after": ["warn", "always-single-line"],
    "css-stylistic/value-list-comma-space-before": ["warn", "never"],
  },
};
