name: check-deps

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  check-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Update Vendor
        run: pnpm i @antfu/eslint-config@latest

      - name: Check Dependencies
        run: pnpm vitest -r packages/zinkawaii deps.test.ts
